[package]
name = "psbt"
version = "0.7.1"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Partially signed bitcoin transaction v0-2 library (bip174, bip370, bip371)"
repository = "https://github.com/LNP-BP/descriptor-wallet"
homepage = "https://github.com/LNP-BP/descriptor-wallet/tree/master/psbt"
keywords = ["bitcoin", "wallet", "cryptocurrency", "psbt", "taproot"]
categories = ["cryptography::cryptocurrencies", "encoding", "parsing"]
readme = "README.md"
edition = "2018"
exclude = []

[dependencies]
amplify = "3.12.0"
strict_encoding = ">=1.8.0-rc.11" # TODO: Make it optional
bitcoin = { version = "0.28.0", features = ["base64"] }
miniscript_crate = { package = "miniscript", version = "7.0.0", optional = true }
descriptors = { version = ">=0.7.0", path = "../descriptors", default-features = false }
bitcoin_scripts = { version = "0.7.0", path = "../scripts" }
bitcoin_hd = { version = "0.7.0", path = "../hd" }
bitcoin_onchain = { version = "0.7.0", path = "../onchain" }
serde_crate = { package = "serde", version = "1", optional = true }
serde_with = { version = "1.12", optional = true }

[dev-dependencies]
strict_encoding_test = "1.8.0"

[features]
default = ["miniscript"]
all = ["sign", "miniscript", "serde"]
miniscript = ["miniscript_crate", "descriptors/miniscript", "bitcoin_scripts/miniscript", "bitcoin_onchain/miniscript"]
sign = ["bitcoin/rand"]
serde = ["serde_crate", "serde_with", "bitcoin/serde", "bitcoin_scripts/serde", "bitcoin_hd/serde"]
